// flow-typed signature: e3819f32f7a70dfd9c6c0ad7e7001f62
// flow-typed version: <<STUB>>/node-fetch_v^1.6.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your workW with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-fetch' {
  declare module.exports: (url: string, options?: {}) => Promise<any>;
}


